services:
  app:
    build: .
    ports:
      - "8001:8001"

  mock_chat:
    build:
      context: ./mock_chat_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - "GF_SECURITY_ADMIN_USER=pyconIT2025"
      - "GF_SECURITY_ADMIN_PASSWORD=workshop"
    volumes:
      - "./grafana_datasources.yaml:/etc/grafana/provisioning/datasources/prometheus_docker-compose.yaml"


